### ISSUE TITLE
It's not compiling on my Arch Linux anymore

### ISSUE THREAD

**Issue by gustavolinux** [jgeumlek/MoltenGamepad#40]
Hi guys, I'm still testing MoltenGamepad, not so frequently as I should cause I'm having a lot of personal problems and Brazil is not in the best financial days... anyway... I tried a version from Ryochan archive, which worked very good considering how response it's to the relative mouse input, but there is a little bug(tested only on my Xubuntu) which makes my mouse pointer go slowly to the top left corner all the time...

there is his archive if you guys wanna test it:
https://drive.google.com/open?id=0B6yGHDx0CFzDakR3SzJHLW1VUjg

Back to the compile issue, I just can not compile MoltenGamepad on Arch Linux anymore(which is strange cause it compiles fine on Xubuntu), the output is always the same:

```
make
compiling source/core/output_slot.cpp...
In file included from source/core/output_slot.cpp:1:0:
source/core/output_slot.h:35:29: error: ‘std::function’ has not been declared
   void for_all_devices(std::function<void (std::shared_ptr<input_source>&)> func);
                             ^~~~~~~~
source/core/output_slot.h:35:37: error: expected ‘,’ or ‘...’ before ‘<’ token
   void for_all_devices(std::function<void (std::shared_ptr<input_source>&)> func);
                                     ^
make: *** [Makefile:60: source/core/output_slot.o] Error 1
```

If you guys want to take a look...

**Comment by jgeumlek** [comment]
Ah, yep, seeing it on my end too. I just put up a quick fix, just needed to include the functional header. Thanks for notifying.
